
project_id = "vxvjkqvssehnxdpyrdim"
[api]
enabled = true
[db]
shadow_database_schema = "shadow"
[db.pooler]
enabled = true
[functions]
[functions.generate-career-insights]
[functions.generate-interview-prep]
[functions.ai-candidate-screening]
[functions.get-elevenlabs-agents]
[functions.get-openai-credits]
[functions.generate-job-details]
[functions.generate-profile-from-resume]
[functions.generate-profile-from-gemini]
[functions.parse-resume]
[functions.parse-resume-with-gemini]
[functions.calculate-match-score]
[functions.generate-skills-languages]
[functions.parse-resume-with-officeparser]
[functions.parse-resume-with-llmwhisperer]
[functions.parse-resume-with-mammoth]
[realtime]
enabled = false
[storage]
file_size_limit = "50MiB"
