
import { cn } from '@/lib/utils';
import { Sparkles } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../ui/tooltip';

interface AIGeneratedProps {
  children: React.ReactNode;
  className?: string;
}

const AIGenerated: React.FC<AIGeneratedProps> = ({ children, className }) => {
  return (
    <div className={cn('border-l-2 border-primary pl-4', className)}>
      <div className="mb-2">
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className="inline-flex items-center gap-1.5 text-xs text-primary">
                <Sparkles className="h-3 w-3" />
                <span>AI Generated</span>
              </div>
            </TooltipTrigger>
            <TooltipContent>
              <p>This content was generated by AI</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </div>
      {children}
    </div>
  );
};

export default AIGenerated;
