// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxvjkqvssehnxdpyrdim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4dmprcXZzc2VobnhkcHlyZGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTI0NzksImV4cCI6MjA2MDIyODQ3OX0.zzn1nN546Bc5BtQyEnfZ4IeBblEax7lslzw4lyzCOx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);